In [2]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jella\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [5]:
dataset = pd.read_csv("training.1600000.processed.noemoticon.csv" , encoding= 'ISO-8859-1')

In [6]:
dataset.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [7]:
col_names = ['target' , 'id' , 'date' , 'flag' , 'user' , 'text']
dataset.columns = col_names

In [8]:
dataset.head()

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [9]:
dataset.shape

(1599999, 6)

In [10]:
#checking for missing values
dataset.isnull().sum()

target    0
id        0
date      0
flag      0
user      0
text      0
dtype: int64

In [11]:
# Distribution of tweets
dataset['target'].value_counts()

target
4    800000
0    799999
Name: count, dtype: int64

In [12]:
# Converting 0 to -ve and 4 to +ve
dataset['target'] = dataset['target'].map({0:0 , 4:1})

In [13]:
dataset['target'].value_counts()

target
1    800000
0    799999
Name: count, dtype: int64

In [ ]:
# Stemming

stremmer = PorterStemmer()

def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content) # Cleans the text (removes symbols, punctuation)
    stemmed_content = stemmed_content.lower()   #Lowercases it
    stemmed_content = stemmed_content.split()   
    stemmed_content = [stremmer.stem(word) for word in stemmed_content if not word in stopwords.words('english')]  #Removes stopwords
    stemmed_content = ' '.join(stemmed_content)    #Stems words to their root form
    return stemmed_content

In [ ]:
# applying streaming to dataset.
dataset['text'] = dataset['text'].apply(stemming)

KeyboardInterrupt:

In [15]:
dataset.head()

,target,id,date,flag,user,text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [ ]:
x = dataset['text']  # contain input data
y = dataset['target']  # contain output like [0,1]

In [ ]:
# splitting the dataset
# This data is used to train the model.
# This data is used to test the performance of the trained model.
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0)

In [22]:
# convert textual data to numerical data
vectorizer = TfidfVectorizer()
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [23]:
print(x_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15188453 stored elements and shape (1279999, 588998)>
  Coords	Values
  (0, 283675)	0.11963044873134729
  (0, 567443)	0.2117590432241851
  (0, 546431)	0.13110375568900662
  (0, 218982)	0.17560132527703673
  (0, 217891)	0.13830752789131484
  (0, 508632)	0.1865617459839415
  (0, 486042)	0.15429339772493936
  (0, 364585)	0.16075477058257603
  (0, 331509)	0.4827791362717877
  (0, 542850)	0.3941117269212658
  (0, 230549)	0.18237085926222382
  (0, 522999)	0.12969477325997483
  (0, 497103)	0.36145902204060715
  (0, 213371)	0.4691562640762748
  (1, 372608)	0.26682925664941753
  (1, 537237)	0.7375855377011513
  (1, 244119)	0.6202980915414966
  (2, 88573)	0.5163168725911714
  (2, 219086)	0.20861007959696407
  (2, 384508)	0.24859958550655706
  (2, 366615)	0.3956805935259804
  (2, 524027)	0.6866832135425449
  (3, 247781)	0.3993877526950337
  (3, 416269)	0.47938639525150156
  (3, 516120)	0.2951126194653137
  :	:
  (1279996, 200539)	0.36513523864462977
  (1279996, 368679)	0.6332121865899873
  (1279997, 325745)	0.15691809476781246
  (1279997, 528406)	0.1658257818915137
  (1279997, 400698)	0.147519025780502
  (1279997, 484728)	0.12571321402256222
  (1279997, 345573)	0.12274859828960134
  (1279997, 581402)	0.21216735835705394
  (1279997, 327451)	0.2043744915391865
  (1279997, 436992)	0.16699410569265366
  (1279997, 559416)	0.15943972511236432
  (1279997, 356755)	0.17710777282850662
  (1279997, 75500)	0.16079285119807193
  (1279997, 370107)	0.17649936910111724
  (1279997, 417280)	0.4163832514439701
  (1279997, 132460)	0.19068432153361467
  (1279997, 474958)	0.2982873364137971
  (1279997, 11365)	0.31432156428188035
  (1279997, 524868)	0.38577136488240416
  (1279997, 65096)	0.3470614775410691
  (1279998, 364585)	0.24791223640478252
  (1279998, 387130)	0.21212399919101982
  (1279998, 219323)	0.3460523465782378
  (1279998, 508303)	0.4684707060975534
  (1279998, 468228)	0.7445306595192318

In [24]:
# Training the model
model = LogisticRegression()
model.fit(x_train , y_train)

LogisticRegression()

In [25]:
# Testing the model
y_pred = model.predict(x_test)
print(accuracy_score(y_test , y_pred))

0.79903125

In [26]:
# Function to predict the sentiment
def predict_sentiment(text):
    text = re.sub('[^a-zA-Z]',' ',text) # removing not a-z and A-Z
    text = text.lower()
    text = text.split() 
    text = [stremmer.stem(word) for word in text if not word in stopwords.words('english')]
    text = ' '.join(text)
    text = [text]
    text = vectorizer.transform(text)   
    sentiment = model.predict(text)
    if sentiment == 0:
        return "Negative"
    else:
        return "Positive"

In [27]:
# Testing the model
print(predict_sentiment("I hate you"))
print(predict_sentiment("I love you"))

Negative
Positive

In [28]:
# Save the model
import pickle
pickle.dump(model , open('model.pkl' , 'wb'))

In [29]:
pickle.dump(vectorizer , open('vectorizer.pkl' , 'wb'))